# Generated by Django 4.1.1 on 2022-10-14 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('orientacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('orientacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='semaforo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoA', models.CharField(max_length=50)),
                ('numA', models.IntegerField(max_length=10)),
                ('tipoB', models.CharField(max_length=50)),
                ('numB', models.IntegerField(max_length=10)),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Via',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionDatos.calle')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionDatos.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField(max_length=5)),
                ('placa', models.CharField(max_length=50)),
                ('propietatio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionDatos.propietario')),
            ],
        ),
    ]
